version: '3'

services: 
  web:
    build: .
    image: php:7.2-apache
    container_name: comanda_php
    depends_on: 
      - db
    volumes: 
      - ".:/var/www/html/"
    ports: 
      - "3000:80"
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    container_name: comanda_sql
    volumes:
      - "./docs:/docs"
    environment:
      MYSQL_ROOT_PASSWORD: 2528
    ports:
      - "3306:3306"
